import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Provider from '@/components/provider/Provider';
import { Props } from '@/types/childrenPropsType';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        {/* 헤더?? */}
        <Provider>{children}</Provider>
        {/* 푸터?? */}
      </body>
    </html>
  );
}
